name: SauceDemoTest

on:
  push:
    branches:
      - main  # Runs the workflow when changes are pushed to main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use the version your project requires

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Playwright report
        run: npx playwright show-report

      - name: Deploy report to GitHub Pages
        if: success()  # Only runs if tests pass
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Directory with the HTML report
          publish_branch: main  # Branch for GitHub Pages
